UPDATE ENDERECO 
SET LOGRADOURO = 'Rua DBC'
WHERE ID_ENDERECO = 1 OR ID_ENDERECO = 2;

UPDATE ENDERECO 
SET NUMERO  = 999999
WHERE ID_ENDERECO = 4;

DELETE FROM ENDERECO e WHERE e.ID_ENDERECO = (SELECT MAX(e2.ID_ENDERECO) FROM ENDERECO e2); 

DELETE FROM ENDERECO e WHERE e.NUMERO = 999999; 

DELETE FROM ENDERECO 
WHERE ID_ENDERECO = 3 OR ID_ENDERECO = 2;

SELECT * FROM ENDERECO e;