-- RIGHT JOIN
SELECT * FROM PESSOA p RIGHT JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA;

SELECT * FROM PESSOA p 
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
RIGHT JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA p 
RIGHT JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
RIGHT JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

-- FULL JOIN
SELECT * FROM PESSOA p FULL JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA;

SELECT * FROM PESSOA p 
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
FULL JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA p 
FULL JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
FULL JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

-- EXISTS
SELECT * FROM PESSOA p 
WHERE EXISTS (SELECT * FROM PESSOA_X_PESSOA_ENDERECO pxpe 
WHERE PXPE.ID_PESSOA = P.ID_PESSOA);

-- ULTIMA QUESTAO
SELECT P.ID_PESSOA, P.NOME, EP.ID_ENDERECO, EP.LOGRADOURO FROM PESSOA p 
JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

