-- RIGHT JOIN
SELECT * FROM PESSOA p RIGHT JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA;

SELECT * FROM PESSOA p 
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
RIGHT JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA p 
RIGHT JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
RIGHT JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

-- FULL JOIN
SELECT * FROM PESSOA p FULL JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA;

SELECT * FROM PESSOA p 
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
FULL JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

SELECT * FROM PESSOA p 
FULL JOIN CONTATO c ON C.ID_PESSOA = P.ID_PESSOA
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_PESSOA = P.ID_PESSOA 
FULL JOIN ENDERECO_PESSOA ep ON PXPE.ID_ENDERECO = EP.ID_ENDERECO;

-- EXISTS
SELECT * FROM PESSOA p 
WHERE EXISTS (SELECT * FROM PESSOA_X_PESSOA_ENDERECO pxpe 
WHERE PXPE.ID_PESSOA = P.ID_PESSOA);

-- UNION
SELECT ID_PESSOA AS ID, NOME
FROM PESSOA
UNION
SELECT ID_ENDERECO AS ID, LOGRADOURO
FROM ENDERECO_PESSOA;
