SELECT * FROM VEM_SER.PAIS ORDER BY NOME DESC;

SELECT e.LOGRADOURO, e.CEP FROM VEM_SER.ENDERECO e WHERE UPPER(e.LOGRADOURO) LIKE 'A%';

SELECT * FROM VEM_SER.ENDERECO e WHERE e.CEP LIKE '%0';

SELECT * FROM VEM_SER.ENDERECO e WHERE e.NUMERO >= 1 AND e.NUMERO <=100;

SELECT * FROM VEM_SER.ENDERECO e WHERE UPPER(e.LOGRADOURO) LIKE 'RUA%' ORDER BY e.CEP DESC;

SELECT COUNT(*) FROM VEM_SER.ENDERECO e; 

SELECT COUNT(*) FROM VEM_SER.ENDERECO e GROUP BY e.ID_CIDADE;