--Criação da Sequência
CREATE SEQUENCE SEQ_PAIS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_ESTADO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_CIDADE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_BAIRRO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE SEQ_ENDERECO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
-- Inserções
-- PAIS
INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.NEXTVAL, 'Brasil');
INSERT INTO VEM_SER.PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.NEXTVAL, 'Espanha');
-- ESTADO
INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'Rio de Janeiro');
INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 1, 'São Paulo');
INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'Madri');
INSERT INTO VEM_SER.ESTADO
(ID_ESTADO, ID_PAIS, NOME)
VALUES(SEQ_ESTADO.NEXTVAL, 2, 'Cataluna');
-- CIDADE
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 1, 'Rio de Janeiro');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 1, 'Fribugo');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 2, 'São Paulo');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 2, 'Bauru');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 3, 'Atie');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 3, 'Aashe');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 4, 'Zyra');
INSERT INTO VEM_SER.CIDADE
(ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_CIDADE.NEXTVAL, 4, 'Gnar');
-- BAIRRO 
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 1, 1, 'Ashad');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 1, 1, 'Asjd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 2, 1, 'Ateste');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 2, 1, 'addasd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 3, 2, 'Adsa');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 3, 2, 'assdsjd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 4, 2, 'fggvcxe');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 4, 2, 'sddfsasd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 5, 3, 'eefhad');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 5, 3, 'dssfdd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 6, 3, 'Arewrte');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 6, 3, 'weqewsd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 7, 4, 'bfdvva');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 7, 4, 'fdsfefd');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 8, 4, 'hdfve');
INSERT INTO VEM_SER.BAIRRO
(ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
VALUES(SEQ_BAIRRO.NEXTVAL, 8, 4, 'dgvvsd');
-- Endereços
INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'Rua dos Exemplos', 123, 'Apto 101', '12345-678');
INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 1, 1, 'Avenida dos Testes', 456, 'Bloco B', '98765-432');
INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 2, 1, 'Rua Principal', 789, NULL, '54321-876');
INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 2, 1, 'Rua Secundária', 1011, 'Casa 2', '87654-321');
INSERT INTO VEM_SER.ENDERECO 
(ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (SEQ_ENDERECO.NEXTVAL, 3, 2, 'Rua Amor', 11, 'Casa 3', '87654-320');
-- Fiz apenas 5 para não ficar uma repetição muito longa e desnecessária (o total teria 16 inserções basicamente iguais)




